amcl:
  ros__parameters:
    use_sim_time: False
    
    # 全局定位
    alpha1: 0.2  # 旋转噪声来自旋转
    alpha2: 0.2  # 旋转噪声来自平移
    alpha3: 0.2  # 平移噪声来自平移
    alpha4: 0.2  # 平移噪声来自旋转
    alpha5: 0.2  # 平移噪声
    
    base_frame_id: "base_link"
    beam_skip_distance: 0.5
    beam_skip_error_threshold: 0.9
    beam_skip_threshold: 0.3
    
    do_beamskip: false
    global_frame_id: "map"
    
    # 激光配置
    lambda_short: 0.1
    laser_likelihood_max_dist: 2.0
    laser_max_range: 12.0
    laser_min_range: 0.15
    laser_model_type: "likelihood_field"
    
    # 定位质量
    max_beams: 60
    max_particles: 2000
    min_particles: 500
    
    odom_frame_id: "odom"
    pf_err: 0.05
    pf_z: 0.99
    
    recovery_alpha_fast: 0.0
    recovery_alpha_slow: 0.0
    resample_interval: 1
    
    # 机器人模型
    robot_model_type: "differential"  # 差分驱动
    
    save_pose_rate: 0.5
    
    sigma_hit: 0.2
    
    tf_broadcast: true
    transform_tolerance: 1.0
    
    # 更新阈值
    update_min_a: 0.2  # 角度变化阈值(弧度)
    update_min_d: 0.25  # 距离变化阈值(米)
    
    z_hit: 0.5
    z_max: 0.05
    z_rand: 0.5
    z_short: 0.05
    
    # 初始姿态
    set_initial_pose: false
    initial_pose:
      x: 0.0
      y: 0.0
      z: 0.0
      yaw: 0.0
